baseURL = 'https://crcresearch.github.io/laserpulse-rp-toolkit/'
languageCode = 'en-us'
title = 'LASER PULSE Reasearch & Practitioner Partnership Toolkit'
theme = "ptTheme"

RelativeURLs=true
CanonifyURLs=true
