baseURL = 'https://crcresearch.github.io/laserpulse-rp-toolkit/'
languageCode = "en-us"
title = "Hugo Cards"
theme = "hugo-cards"
themesDir = "../.."
paginate = 6

RelativeURLs=true
CanonifyURLs=true

[params]
  builtBy = "bool"
  defaultImage = "gopher.jpg"

  facebook = ""
  quora = ""
  twitter = "http://twitter.com/bul_ikana"
  github = "http://github.com/bul-ikana"
  email = ""

  fbLikeBox = ""
  fbAppId = ""
  fbPageUrl = ""
  fbPageTitle = ""

  disqus = ""
  
  custom_css = ["css/custom.css"]

  googleAnalytics = 'G-WFZ7YLGQP3'

  [params.analytics]
    type="GA4"
    trackingID = "G-WFZ7YLGQP3"

  [params.copyright]
     name = "bool"
     link = "https://bool.netlify.com"

