name: GitHub Pages

on:
  push:
    branches:
      - master  # Set a branch name to trigger deployment
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.85.0'

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: npm install
        run: npm ci

      - name: Fetch data from Airtable API
        run: |
          OUTPUT_FILE_NAME=data_`date +%s`.json
          npm run --silent airtable | tee data/$OUTPUT_FILE_NAME
          ln -sf $OUTPUT_FILE_NAME data/blindspots.json
        env:
          AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
          AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}

      - name: Push changes to repo
        run: |
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "${{ github.actor }}"
          git add data/$OUTPUT_FILE_NAME data/blindspots.json
          git status
          git commit -m "triggered automated Aritable data fetch on $(date)"
          git push

